"""Add description to Document

Revision ID: e5ef27b55833
Revises: 7d678a59c51a
Create Date: 2025-09-30 05:11:46.175627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ef27b55833'
down_revision = '7d678a59c51a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'description')
    # ### end Alembic commands ###
